test commit
bmstu-iu8-2018-project/wallet pull request #1
Opened 2018-10-10 18:19 UTC by moguchev

2018-10-10 18:33 UTC, drewxa approved these changes

2018-10-23 10:32 UTC, drewxa requested changes
Натравите на ваш код cmake-format. И определитель с кодстайлом. Пока я вижу кучу взятого откуда-то из вне кода, вашего мало....

2018-10-23 10:32 UTC, drewxa commented on includes/Crypto.h
> +#ifndef CRYPTO_H
Лучше назвать как-то CryptoUtils
Почему реализация в .h файле?

2018-10-23 10:32 UTC, drewxa commented on includes/Crypto.h
> +std::string SHA256(const std::string& string)
Надо функции завернуть в namespace

2018-10-23 10:32 UTC, drewxa commented on includes/Key.h
> +        std::string hash = "00"; // �������� ���� 0x00, �������� ���� 0�0f, Namecoin ���� 0�34;
преобразовать файл в UTF-8, а то комментарии не читабельны

2018-10-23 10:32 UTC, drewxa commented on includes/Key.h
> +    void make_address()
эта функция точно должна быть публичной?

2018-11-21 07:58 UTC, moguchev reviewed
rolled back CryptoUtils

2018-12-01 17:41 UTC, drewxa requested changes

2018-12-01 17:41 UTC, drewxa commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.1)
почему не hunter?

2018-12-01 17:41 UTC, drewxa commented on includes/CryptoUtils.hpp
> +#pragma once
`#pragma once` не нужна если есть `#ifndef CRYPTO_UTILS_HPP`

2018-12-01 17:41 UTC, drewxa commented on includes/CryptoUtils.hpp
> +    static const char* Base58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
`const char Base58[]`
static не нуден

2018-12-01 17:41 UTC, drewxa commented on includes/CryptoUtils.hpp
> +        std::vector<byte> a(sizeof(i));
заиспользуйте тут http://www.cplusplus.com/reference/type_traits/

2018-12-01 17:41 UTC, drewxa commented on includes/CryptoUtils.hpp
> +        std::vector<byte> a(sizeof(i));
проверку на тип

2018-12-01 17:41 UTC, drewxa commented on includes/CryptoUtils.hpp
> +        ss << std::hex << std::setw(2 * sizeof(T)) << std::setfill('0') << static_cast<int>(s);
не нравится мне эта реализация. с одной стороны шаблоны, а стругой стороны работает только для` int`

2018-12-01 17:41 UTC, drewxa commented on includes/CryptoUtils.hpp
> +        T x;
type_traits на проверку типа

2018-12-01 17:41 UTC, drewxa commented on includes/Key.hpp
> +using namespace cu;
в hpp файле `using namespace`? тут вы рискуете попасть на снижение оценки

2018-12-01 17:41 UTC, drewxa commented on includes/NetworkUtils.hpp
> +const std::string BTCTEST_NETWORK = "BTCTEST/";
std::string_view

2018-12-01 17:41 UTC, drewxa commented on includes/Script.hpp
> +    std::vector<byte> script_;
Соглашения в стиле так и нет. То `_Address`, то `script_`

2018-12-01 17:41 UTC, drewxa commented on includes/TxIn.hpp
> +
много пустых строк

2018-12-01 17:41 UTC, drewxa commented on includes/TxOut.hpp
> +    std::string get_addres() const;
две s

2018-12-01 17:41 UTC, drewxa commented on includes/usb_monitor.hpp
> +    //Creates a single instance of the class usb_monitor
после // пробел

2018-12-01 17:41 UTC, drewxa commented on includes/usb_monitor.hpp
> +	static usb_monitor* create(bool monitor_hard_drives = false);
поехали отступы

2018-12-01 17:41 UTC, drewxa commented on includes/usb_monitor.hpp
> +	boost::function<void(char)> on_device_added_;
почему boost а не Std ?

2018-12-01 17:41 UTC, drewxa commented on offline_wallet/informationwindow.cpp
> +void InformationWindow::finde_usb_device()
`find_`

2018-12-01 17:41 UTC, drewxa commented on offline_wallet/informationwindow.cpp
> +    path += ":/";
А как у вас обстоят дела с кроссплатформенностью?

2018-12-01 17:41 UTC, drewxa commented on offline_wallet/mainwindow.cpp
> +    while (it.hasNext())
тут у вас идет поиск файла во всех поддиректориях. это долгая операция. значит её надо выполнять асинхронно

2018-12-01 17:41 UTC, drewxa commented on offline_wallet/transactionwindow.cpp
> +    QString path = tx_dir_.path() + '/' + ui->tx_id_box->currentText() + "/tx.dat";
ну не катит ` + '/' + `
есть же метод append() или подобный, который сам добавляет нужный слеш

2018-12-01 17:41 UTC, drewxa commented on online_wallet/informationwindow.cpp
> +    if (index == static_cast<int>(Requests::address_balanse))
`address_balanCe`

2018-12-01 17:41 UTC, drewxa commented on online_wallet/informationwindow.cpp
> +void InformationWindow::on_boxRequests_currentIndexChanged(int index)
Requests index`

2018-12-01 17:41 UTC, drewxa commented on online_wallet/informationwindow.cpp
> +    if (index == static_cast<int>(Requests::address_balanse))
Есть такое дело как switch

2018-12-01 17:41 UTC, drewxa commented on online_wallet/maketransactionwindow.cpp
> +    QLineEdit *previous_output = new QLineEdit(&dialog);
умные указатели где?

2018-12-01 17:41 UTC, drewxa commented on src/NetworkUtils.cpp
> +
`namespace nu {`

2018-12-01 17:41 UTC, drewxa commented on src/Script.cpp
> +Script::Script(Script&& other)
`= default`

2018-12-01 17:41 UTC, drewxa commented on src/Script.cpp
> +Script::Script(const std::vector<byte>& bytes)
А где конструктор `Script::Script(std::vector<byte>&& bytes)`

2018-12-01 17:41 UTC, drewxa commented on src/Script.cpp
> +Script& Script::operator=(const Script& other)
`= default`

2018-12-01 17:41 UTC, drewxa commented on online_wallet/informationwindow.cpp
> +void InformationWindow::on_boxRequests_currentIndexChanged(int index)
так. тут посылаются какие-то интернет запросы, они ассинхронные?

2018-12-01 17:42 UTC, merged